name: tokenized-strategy-ape-mix

plugins:
  - name: solidity
  - name: vyper
  - name: etherscan
  - name: hardhat
  - name: infura
  - name: alchemy

default_ecosystem: ethereum
dependencies:
  - name: openzeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.8.2
  - name: yearn-vaults
    github: yearn/yearn-vaults-v3
    branch: master
  - name: tokenized-strategy
    github: yearn/tokenized-strategy
    branch: test
    contracts_folder: src
    exclude:
     - src/test/**/*
  - name: periphery
    github: schlagonia/tokenized-strategy-periphery
    branch: master

solidity:
  import_remapping:
    - "@openzeppelin/contracts=openzeppelin/v4.8.2"
    - "@yearn-vaults=yearn-vaults/master"
    - "@tokenized-strategy=tokenized-strategy/test"
    - "@periphery=periphery/master"

ethereum:
  default_network: mainnet-fork
  mainnet_fork:
    default_provider: hardhat

hardhat:
  fork:
    ethereum:
      mainnet:
        upstream_provider: infura